export const desc = 'Bienvenidos a la Unidad Educativa Thomas Russell Crampton, un espacio donde la innovación y la excelencia educativa se encuentran para forjar el futuro de las nuevas generaciones. En nuestra institución, nos enorgullece ofrecer un entorno de aprendizaje único, diseñado para inspirar la curiosidad, el pensamiento crítico y la pasión por el conocimiento en cada uno de nuestros estudiantes. Al aspirar a formar parte de nuestra comunidad, te embarcas en un viaje educativo sin precedentes, donde cada experiencia está cuidadosamente elaborada para expandir tus horizontes y desafiar tus límites. Aquí, en Thomas Russell Crampton, no solo te preparamos para afrontar los desafíos del mañana, sino que te equipamos con las herramientas necesarias para ser un líder innovador y un ciudadano global responsable. Te invitamos a unirte a nosotros en esta aventura transformadora, donde tu potencial no conoce límites y tu pasión por aprender se enciende con cada nuevo día.'

export const required_fields = [
    'first_name',
    'fLast_name',
    'id_card',
    'age',
    'number',
    'email',
    'last_institution',
    'behavior_qualification',
    'address',
    'level_id',
    'father_names',
    'father_phone',
    'father_occupation',
    'mother_names',
    'mother_phone',
    'mother_occupation',
]

export const contact_fields = {
    first_name: '',
    second_name: '',
    fLast_name: '',
    sLast_name: '',
    id_card: '',
    age: '',
    number: '',
    email: '',
    last_institution: '',
    behavior_qualification: '',
    address: '',
    level_id: '',
    father_names: '',
    father_phone: '',
    father_occupation: '',
    mother_names: '',
    mother_phone: '',
    mother_occupation: '',
};